Repository DSWU-UMC-8th/UMC-8th-TEAM-WEB2-FE, pull requests merged in 2025-05, with the labels that each got.

#2 [Init] 프로젝트 초기 세팅
  .github/pull_request_template.md
  ReviewInClass-FE/.gitignore
  ReviewInClass-FE/README.md
  ReviewInClass-FE/eslint.config.js
  ReviewInClass-FE/index.html
  ReviewInClass-FE/package.json
  ReviewInClass-FE/pnpm-lock.yaml
  ReviewInClass-FE/public/fonts/Pretendard-Bold.woff2
  ReviewInClass-FE/public/fonts/Pretendard-Medium.woff2
  ReviewInClass-FE/public/fonts/Pretendard-Regular.woff2
  ReviewInClass-FE/public/fonts/Pretendard-SemiBold.woff2
  ReviewInClass-FE/src/App.css
  ReviewInClass-FE/src/App.tsx
  ReviewInClass-FE/src/apis/axios.ts
  ReviewInClass-FE/src/assets/arrow/icon-arrow-down.svg
  ReviewInClass-FE/src/assets/arrow/icon-arrow-right.svg
  ReviewInClass-FE/src/assets/arrow/icon-arrow-swap_vert.svg
  ReviewInClass-FE/src/assets/arrow/icon-arrow-up.svg
  ReviewInClass-FE/src/assets/banner/banner-1.png
  ReviewInClass-FE/src/assets/banner/banner-2.png
  ReviewInClass-FE/src/assets/banner/banner-3.png
  ReviewInClass-FE/src/assets/banner/banner-4.png
  ReviewInClass-FE/src/assets/icon-empty-result.svg
  ReviewInClass-FE/src/assets/icon-logo.svg
  ReviewInClass-FE/src/assets/icon-pic-select.svg
  ReviewInClass-FE/src/assets/navbar/icon-navbar-home.svg
  ReviewInClass-FE/src/assets/navbar/icon-navbar-latest.svg
  ReviewInClass-FE/src/assets/navbar/icon-navbar-popular.svg
  ReviewInClass-FE/src/assets/navbar/icon-navbar-search.svg
  ReviewInClass-FE/src/assets/navbar/icon-navbar-variant5.svg
  ReviewInClass-FE/src/assets/star/icon-star-empty.svg
  ReviewInClass-FE/src/assets/star/icon-star-full.svg
  ReviewInClass-FE/src/assets/star/icon-star-half.svg
  ReviewInClass-FE/src/assets/thumbs/icon-thumbs-color-down.svg
  ReviewInClass-FE/src/assets/thumbs/icon-thumbs-color-up.svg
  ReviewInClass-FE/src/assets/thumbs/icon-thumbs-down.svg
  ReviewInClass-FE/src/assets/thumbs/icon-thumbs-up.svg
  ReviewInClass-FE/src/components/common/Navbar.tsx
  ReviewInClass-FE/src/index.css
  ReviewInClass-FE/src/layouts/HomeLayout.tsx
  ReviewInClass-FE/src/main.tsx
  ReviewInClass-FE/src/pages/CreateReview.tsx
  ReviewInClass-FE/src/pages/Detail.tsx
  ReviewInClass-FE/src/pages/Main.tsx
  ReviewInClass-FE/src/pages/NotFound.tsx
  ReviewInClass-FE/src/pages/Review.tsx
  ReviewInClass-FE/src/styles/global.css
  ReviewInClass-FE/src/styles/theme.ts
  ReviewInClass-FE/src/vite-env.d.ts
  ReviewInClass-FE/tsconfig.app.json
  ReviewInClass-FE/tsconfig.json
  ReviewInClass-FE/tsconfig.node.json
  ReviewInClass-FE/vite.config.ts
Labels: 🎉 Init

#16 [Feat] notfound 페이지 구현
  ReviewInClass-FE/src/assets/not-found.png
  ReviewInClass-FE/src/pages/NotFound.tsx
Labels: ✨ Feature

#19 [Feat] 강의 작성 페이지 퍼블리싱
  ReviewInClass-FE/index.html
  ReviewInClass-FE/package.json
  ReviewInClass-FE/pnpm-lock.yaml
  ReviewInClass-FE/src/assets/x-icon.svg
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/ClassInfo.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/ImageUpload.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/InputComponent.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/SearchBtn.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/CheckBoxComponent.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/RatingSlider.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/SilderStyle.css
  ReviewInClass-FE/src/components/CreateReview/WriteReview/TextEditor.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/WirteReview.css
  ReviewInClass-FE/src/components/CreateReview/WriteReview/WriteReview.tsx
  ReviewInClass-FE/src/pages/CreateReview.tsx
Labels: ✨ Feature

#20 [Feat] 리뷰 상세 페이지 구현
  ReviewInClass-FE/package.json
  ReviewInClass-FE/pnpm-lock.yaml
  ReviewInClass-FE/src/components/LectureReviewFilterBar.tsx
  ReviewInClass-FE/src/components/RatingSummary.tsx
  ReviewInClass-FE/src/pages/Detail.tsx
Labels: ✨ Feature

#21 [Feat] 리뷰 작성 모달 구현
  ReviewInClass-FE/src/components/CreateReview/ReviewModal.tsx
  ReviewInClass-FE/src/components/common/FloatingBtn.tsx
Labels: ✨ Feature

#22 [Fix] 스크롤 이동 수정
  ReviewInClass-FE/src/components/common/FloatingBtn.tsx
  ReviewInClass-FE/src/components/common/Navbar.tsx
Labels: 🐛 Fix

#23 [Feat] 공통 컴포넌트 추가 구현
  ReviewInClass-FE/package.json
  ReviewInClass-FE/pnpm-lock.yaml
  ReviewInClass-FE/src/App.tsx
  ReviewInClass-FE/src/components/Loading.tsx
  ReviewInClass-FE/src/components/MainReview.tsx
  ReviewInClass-FE/src/components/NoResult.tsx
  ReviewInClass-FE/src/components/common/Navbar.tsx
  ReviewInClass-FE/src/context/SearchContext.tsx
  ReviewInClass-FE/src/data/mainDummyReview.ts
  ReviewInClass-FE/src/hooks/useSearchList.ts
  ReviewInClass-FE/src/pages/Main.tsx
  ReviewInClass-FE/src/pages/NotFound.tsx
  ReviewInClass-FE/src/pages/Review.tsx
Labels: ✨ Feature

#30 [Feat] default axios 생성
  ReviewInClass-FE/.gitignore
  ReviewInClass-FE/src/apis/axios.ts
  ReviewInClass-FE/src/vite-env.d.ts
Labels: ✨ Feature

#33 [Feat] 강의평 등록 api 연동
  ReviewInClass-FE/index.html
  ReviewInClass-FE/public/fonts/Inter_28pt-ExtraBold.ttf
  ReviewInClass-FE/src/apis/createReview.ts
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/ClassInfo.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/FieldLabel.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/ImageUpload.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/InputComponent.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/SearchDropdown.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/SectionTitle.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/TagBadge.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/CheckBoxComponent.tsx
  ReviewInClass-FE/src/components/CreateReview/WriteReview/WirteReview.css
  ReviewInClass-FE/src/components/CreateReview/WriteReview/WriteReview.tsx
  ReviewInClass-FE/src/constants/periodOptions.ts
  ReviewInClass-FE/src/enums/StudyPeriod.ts
  ReviewInClass-FE/src/hooks/useDebounce.ts
  ReviewInClass-FE/src/hooks/useModal.ts
  ReviewInClass-FE/src/hooks/useReviewForm.ts
  ReviewInClass-FE/src/hooks/useSearch.ts
  ReviewInClass-FE/src/pages/CreateReview.tsx
  ReviewInClass-FE/src/styles/global.css
  ReviewInClass-FE/src/types/reviewCreate.ts
Labels: ✨ Feature, ♻️refactor

#35 [Fix] 텍스트 에디터 html 태그 제거
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/ClassInfo.tsx
  ReviewInClass-FE/src/components/CreateReview/ClassInfo/SearchDropdown.tsx
  ReviewInClass-FE/src/pages/CreateReview.tsx
Labels: 🐛 Fix

#38 [Fix] 메인페이지 및 상세 페이지 배너 수정
  ReviewInClass-FE/src/components/common/Banner/Banner.tsx
  ReviewInClass-FE/src/pages/Detail.tsx
Labels: 🐛 Fix

#41 [Fix] 검색 및 페이지네이션 수정
  ReviewInClass-FE/src/hooks/useSearchList.ts
  ReviewInClass-FE/src/pages/Review.tsx
Labels: 🐛 Fix
